services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mResvXDs9Gk89Ef
  gate-simulator:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "9999:9999"
    volumes:
      - ./gate-simulator:/app
    command: sh -c "npm install && npm start"








